export default {
  login: "HamzaAziz-1",
  id: 88493437,
  node_id: "MDQ6VXNlcjg4NDkzNDM3",
  avatar_url: "https://avatars.githubusercontent.com/u/88493437?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/HamzaAziz-1",
  html_url: "https://github.com/HamzaAziz-1",
  followers_url: "https://api.github.com/users/HamzaAziz-1/followers",
  following_url:
    "https://api.github.com/users/HamzaAziz-1/following{/other_user}",
  gists_url: "https://api.github.com/users/HamzaAziz-1/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/HamzaAziz-1/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/HamzaAziz-1/subscriptions",
  organizations_url: "https://api.github.com/users/HamzaAziz-1/orgs",
  repos_url: "https://api.github.com/users/HamzaAziz-1/repos",
  events_url: "https://api.github.com/users/HamzaAziz-1/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/HamzaAziz-1/received_events",
  type: "User",
  site_admin: false,
  name: "Muhammad Hamza Aziz",
  company: null,
  blog: "https://hamza-personal-portfolio.netlify.app/",
  location: "Lahore",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 18,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2021-08-05T12:39:50Z",
  updated_at: "2023-07-12T10:25:39Z",
};